[project]
name = "py-deepseek"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "openai>=2.8.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.0.0",
]
